version: '3.1'
services:
  server:
    image: jormaechea/open-api-mocker
    restart: always
    ports:
      - "5500:5000"
    volumes:
      - ./server/openapi.json:/app/schema.json
  client:
    build: ./client
    restart: always
    ports:
      - "80:80"